### ISSUE TITLE
Setup env (docker)

### ISSUE THREAD

**Issue by alexandregv** [alexandregv/Matcha#1]
Compose:
- api
- front
- db

**Comment by sophiebl** [comment]
- Sass
- React Router

**Comment by alexandregv** [comment]
Switched to a Docker Stack (251e934, a7ac2a3, 7f49d32) and added react-router-dom and node-sass (ac860c9)

Images pushed on DockerHub:
- https://hub.docker.com/r/triinoxys/matcha-front
- https://hub.docker.com/r/triinoxys/matcha-api

Related image, used to init a React App (54baddf):
- https://hub.docker.com/r/triinoxys/node-cli
